export const products = {
  one: {
    slug: "compas-one",
    shortName: "Compás One",
    title: "Compás One",
    kicker: "CRM y operación comercial",
    logo: "/brand/compas-one-logo.svg",
    seoTitle: "CRM para pequeñas empresas y negocios | Compás One",
    seoDescription: "CRM para pequeñas empresas que centraliza clientes, prospectos, conversaciones, agenda, seguimiento, automatizaciones y agentes de IA en una sola plataforma.",
    seoH1: "CRM para pequeñas empresas que organiza clientes, ventas y seguimiento",
    ogImage: "/brand/compas-one-dashboard-1600x900.png",
    schemaType: "SoftwareApplication",
    description: "Compás One es un CRM para negocios que necesitan centralizar clientes y prospectos, ordenar el seguimiento comercial y reducir tareas manuales desde un solo espacio de trabajo.",
    audience: "Pequeñas empresas, negocios de servicios, profesionales y equipos comerciales que atienden clientes todos los días y necesitan dejar atrás el seguimiento disperso entre mensajes, notas, hojas de cálculo y pendientes individuales.",
    solves: [
      "Clientes y prospectos dispersos entre distintos canales y archivos",
      "Oportunidades que se enfrían porque nadie recuerda el siguiente seguimiento",
      "Información comercial sin un historial claro de conversaciones y pendientes",
      "Tareas repetitivas que consumen tiempo del equipo",
      "Falta de visibilidad sobre qué cliente necesita atención y cuál es el siguiente paso",
    ],
    includes: [
      "CRM y gestión centralizada de clientes y contactos",
      "Registro de prospectos, conversaciones, pendientes y seguimiento comercial",
      "Agenda y organización de actividades relacionadas con cada cliente",
      "Automatizaciones para reducir tareas repetitivas",
      "Agentes de IA para ventas, soporte y seguimiento según la configuración del negocio",
    ],
    steps: [
      "Revisamos cómo gestionas hoy clientes, prospectos y seguimientos",
      "Definimos la información y los procesos que conviene centralizar",
      "Configuramos el espacio de trabajo y las automatizaciones prioritarias",
      "Preparamos al equipo para operar el CRM con una rutina clara",
      "Medimos adopción, seguimiento y oportunidades para seguir mejorando",
    ],
    valueHeading: "Un CRM pensado para dar seguimiento sin perder el contexto",
    valueText: "No se trata sólo de guardar contactos. Compás One busca que cada cliente tenga un historial útil, un responsable, pendientes claros y un siguiente paso. Así el equipo puede saber qué ocurrió, qué falta y dónde concentrar la atención comercial.",
    useCasesHeading: "Qué puedes organizar con Compás One",
    useCases: [
      "Prospectos que llegan y todavía no están listos para comprar",
      "Clientes activos que requieren seguimiento, citas o tareas pendientes",
      "Conversaciones comerciales que necesitan continuidad",
      "Actividades del equipo relacionadas con clientes y oportunidades",
      "Procesos repetitivos que pueden apoyarse con automatización e inteligencia artificial",
    ],
    faqs: [
      {
        question: "¿Qué es un CRM y cómo ayuda a una pequeña empresa?",
        answer: "Un CRM organiza la información y el seguimiento de clientes y prospectos en un solo lugar. Ayuda a reducir olvidos, conservar el historial comercial y definir el siguiente paso para cada oportunidad.",
      },
      {
        question: "¿Compás One sirve si hoy llevo mis clientes en mensajes, notas o hojas de cálculo?",
        answer: "Sí. Compás One está pensado para centralizar el seguimiento que suele quedar repartido entre diferentes herramientas. La forma exacta de migrar u organizar la información depende de cómo opere actualmente cada negocio.",
      },
      {
        question: "¿Compás One ayuda a dar seguimiento a prospectos?",
        answer: "Sí. El CRM permite organizar prospectos, registrar contexto y pendientes, y mantener una ruta de seguimiento para que el equipo sepa quién necesita atención y cuál es el siguiente paso.",
      },
      {
        question: "¿Compás One incluye automatizaciones e inteligencia artificial?",
        answer: "Puede incorporar automatizaciones y agentes de IA para apoyar ventas, soporte y seguimiento. Las funciones se configuran según los procesos, límites y necesidades reales de cada negocio.",
      },
    ],
    primaryCtaLabel: "Quiero conocer Compás One",
    directUrl: "https://app.proyectocompas.com",
    directLabel: "Entrar a Compás One",
  },
  academy: {
    slug: "compas-academy",
    shortName: "Compás Academy",
    title: "Compás Academy",
    kicker: "Aprendizaje aplicable",
    logo: "/brand/compas-academy-logo.svg",
    seoTitle: "Academias digitales y capacitación empresarial | Compás Academy",
    seoDescription: "Creamos academias digitales, cursos, rutas de capacitación y experiencias de aprendizaje para empresas, expertos y marcas.",
    seoH1: "Crea una academia digital para capacitar, enseñar y convertir conocimiento en acción",
    ogImage: "/brand/compas-academy-1600x900.png",
    schemaType: "Service",
    description: "Rutas de aprendizaje, cursos y recursos diseñados para que las personas desarrollen capacidades y apliquen lo aprendido dentro de sus propios proyectos.",
    audience: "Personas, equipos y clientes que necesitan aprender herramientas, procesos o habilidades con una ruta clara y una experiencia de aprendizaje organizada.",
    solves: ["Capacitación dispersa", "Cursos sin continuidad ni seguimiento", "Dificultad para convertir conocimiento en acciones", "Necesidad de una academia digital propia"],
    includes: ["Cursos y rutas de aprendizaje", "Recursos descargables", "Seguimiento del alumno", "Experiencias personalizadas", "Integración con el ecosistema Compás"],
    steps: ["Definimos el objetivo de aprendizaje", "Organizamos módulos y recursos", "Configuramos la experiencia académica", "Publicamos y acompañamos la adopción"],
    directUrl: "https://aula.proyectocompas.com/",
    directLabel: "Entrar a Compás Academy",
  },
  creators: {
    slug: "compas-creators",
    shortName: "Compás Creators",
    title: "Compás Creators",
    kicker: "Ideas convertidas en proyectos",
    logo: "/brand/compas-creators-logo.svg",
    seoTitle: "Desarrollo de páginas, cursos y productos digitales | Compás Creators",
    seoDescription: "Creamos páginas web, landing pages, cursos, academias, libros y productos digitales con estructura, diseño, publicación y dirección.",
    seoH1: "Convierte tu experiencia en cursos, libros y productos digitales",
    ogImage: "/og.png",
    schemaType: "Service",
    description: "Acompañamiento para transformar experiencia, conocimiento o una buena historia en un libro, curso, página, academia o producto digital con estructura y dirección.",
    audience: "Personas que tienen experiencia, una historia, conocimiento profesional o una idea valiosa, pero todavía no saben cómo convertirla en un proyecto presentable y comercializable.",
    solves: ["Ideas sin estructura", "Proyectos que no llegan a publicarse", "Falta de identidad, maquetación o plataforma", "Dificultad para convertir experiencia en un producto"],
    includes: ["Definición del proyecto", "Estructura de contenido", "Diseño y dirección visual", "Maquetación o desarrollo digital", "Ruta de publicación y difusión"],
    steps: ["Identificamos qué quieres crear", "Ordenamos la idea y el contenido", "Construimos la pieza o plataforma", "Preparamos publicación, lanzamiento y seguimiento"],
  },
  ia: {
    slug: "compas-ia",
    shortName: "Compás IA",
    title: "Compás IA",
    kicker: "Agentes inteligentes con función",
    logo: "/brand/compas-ia-logo.svg",
    seoTitle: "Agentes de IA para ventas, soporte y seguimiento | Compás IA",
    seoDescription: "Implementamos agentes de IA para ventas, soporte y seguimiento, conectados al conocimiento de tu negocio y con reglas claras de actuación.",
    seoH1: "Agentes de inteligencia artificial para ventas, soporte y seguimiento",
    ogImage: "/og.png",
    schemaType: "Service",
    description: "Agentes inteligentes especializados en ventas, soporte, seguimiento y operación, conectados con el conocimiento de cada negocio y con reglas claras de actuación.",
    audience: "Negocios y equipos que quieren atender mejor, responder más rápido y automatizar tareas sin perder el contexto ni la capacidad de intervención humana.",
    solves: ["Consultas repetitivas", "Prospectos sin respuesta inmediata", "Seguimientos olvidados", "Equipos saturados por tareas de atención"],
    includes: ["Agente de ventas", "Agente de soporte", "Agente de seguimiento", "Base de conocimiento del negocio", "Escalamiento a una persona cuando corresponde"],
    steps: ["Definimos la función del agente", "Cargamos y ordenamos el conocimiento", "Configuramos límites y rutas de escalamiento", "Probamos, publicamos y mejoramos con conversaciones reales"],
  },
};
