export const products = {
  one: {
    slug: "compas-one",
    shortName: "Compás One",
    title: "Compás One",
    kicker: "Operación inteligente",
    logo: "/brand/compas-one-logo.svg",
    description: "Centraliza clientes, conversaciones, agenda, seguimiento, automatizaciones y agentes inteligentes para operar con mayor claridad desde un solo lugar.",
    audience: "Emprendedores, profesionales y equipos que ya atienden clientes y necesitan ordenar la operación, dar seguimiento y reducir tareas manuales.",
    solves: ["Información dispersa entre diferentes canales", "Prospectos sin seguimiento", "Procesos repetitivos que consumen tiempo", "Falta de visibilidad sobre clientes, conversaciones y pendientes"],
    includes: ["CRM y gestión de contactos", "Conversaciones y seguimiento", "Agenda y proyectos", "Automatizaciones", "Agentes inteligentes conectados al conocimiento del negocio"],
    steps: ["Entendemos tu operación actual", "Configuramos el espacio de trabajo", "Conectamos los canales y procesos prioritarios", "Entrenamos al equipo y medimos resultados"],
    directUrl: "https://app.proyectocompas.com",
    directLabel: "Entrar a Compás One",
  },
  academy: {
    slug: "compas-academy",
    shortName: "Compás Academy",
    title: "Compás Academy",
    kicker: "Aprendizaje aplicable",
    logo: "/brand/compas-academy-logo.svg",
    description: "Rutas de aprendizaje, cursos y recursos diseñados para que las personas desarrollen capacidades y apliquen lo aprendido dentro de sus propios proyectos.",
    audience: "Personas, equipos y clientes que necesitan aprender herramientas, procesos o habilidades con una ruta clara y una experiencia de aprendizaje organizada.",
    solves: ["Capacitación dispersa", "Cursos sin continuidad ni seguimiento", "Dificultad para convertir conocimiento en acciones", "Necesidad de una academia digital propia"],
    includes: ["Cursos y rutas de aprendizaje", "Recursos descargables", "Seguimiento del alumno", "Experiencias personalizadas", "Integración con el ecosistema Compás"],
    steps: ["Definimos el objetivo de aprendizaje", "Organizamos módulos y recursos", "Configuramos la experiencia académica", "Publicamos y acompañamos la adopción"],
    directUrl: "https://aula.proyectocompas.com/",
    directLabel: "Entrar a Compás Academy",
  },
  creators: {
    slug: "compas-creators",
    shortName: "Compás Creators",
    title: "Compás Creators",
    kicker: "Ideas convertidas en proyectos",
    logo: "/brand/compas-creators-logo.svg",
    description: "Acompañamiento para transformar experiencia, conocimiento o una buena historia en un libro, curso, página, academia o producto digital con estructura y dirección.",
    audience: "Personas que tienen experiencia, una historia, conocimiento profesional o una idea valiosa, pero todavía no saben cómo convertirla en un proyecto presentable y comercializable.",
    solves: ["Ideas sin estructura", "Proyectos que no llegan a publicarse", "Falta de identidad, maquetación o plataforma", "Dificultad para convertir experiencia en un producto"],
    includes: ["Definición del proyecto", "Estructura de contenido", "Diseño y dirección visual", "Maquetación o desarrollo digital", "Ruta de publicación y difusión"],
    steps: ["Identificamos qué quieres crear", "Ordenamos la idea y el contenido", "Construimos la pieza o plataforma", "Preparamos publicación, lanzamiento y seguimiento"],
  },
  ia: {
    slug: "compas-ia",
    shortName: "Compás IA",
    title: "Compás IA",
    kicker: "Agentes inteligentes con función",
    logo: "/brand/compas-ia-logo.svg",
    description: "Agentes inteligentes especializados en ventas, soporte, seguimiento y operación, conectados con el conocimiento de cada negocio y con reglas claras de actuación.",
    audience: "Negocios y equipos que quieren atender mejor, responder más rápido y automatizar tareas sin perder el contexto ni la capacidad de intervención humana.",
    solves: ["Consultas repetitivas", "Prospectos sin respuesta inmediata", "Seguimientos olvidados", "Equipos saturados por tareas de atención"],
    includes: ["Agente de ventas", "Agente de soporte", "Agente de seguimiento", "Base de conocimiento del negocio", "Escalamiento a una persona cuando corresponde"],
    steps: ["Definimos la función del agente", "Cargamos y ordenamos el conocimiento", "Configuramos límites y rutas de escalamiento", "Probamos, publicamos y mejoramos con conversaciones reales"],
  },
};
