"use client";

import Image from "next/image";
import { useState } from "react";
import HomeGrowth from "./home-growth";

const APP_URL="https://app.proyectocompas.com";
const ACADEMY_URL="https://aula.proyectocompas.com/";

const decisions=[
{id:"operacion",label:"Organizar mi negocio",title:"Tu siguiente paso es Compás One",text:"Centraliza clientes, conversaciones, agenda, seguimiento y automatizaciones en un solo lugar.",href:"/compas-one",cta:"Conocer Compás One",product:"compas-one"},
{id:"aprendizaje",label:"Aprender y capacitarme",title:"Tu siguiente paso es Compás Academy",text:"Avanza con rutas prácticas para convertir conocimiento en acciones concretas.",href:"/compas-academy",cta:"Conocer Compás Academy",product:"compas-academy"},
{id:"conocimiento",label:"Convertir mi experiencia en un proyecto",title:"Tu siguiente paso es Compás Creators",text:"Transforma tu experiencia en un libro, curso, página, academia o producto digital con estructura.",href:"/compas-creators",cta:"Conocer Compás Creators",product:"compas-creators"},
{id:"claridad",label:"Aún no sé qué necesito",title:"Primero encontremos el norte",text:"Cuéntanos qué quieres resolver y el agente de ventas te orientará hacia la ruta adecuada.",href:"#agente-ventas",cta:"Pedir orientación",product:"diagnostico",agent:"sales"},
];

const projects=[
{title:"ETERNI",type:"Marca + academia + contenidos",image:"/portfolio/web-eterni.jpg",alt:"Proyecto ETERNI"},
{title:"ASTRA Retiro",type:"Orientación + captación + seguimiento",image:"/portfolio/web-astra-retiro.jpg",alt:"Proyecto ASTRA Retiro"},
{title:"AG Business Networking",type:"Academia + evaluaciones + soporte",image:"/portfolio/web-business-networking.jpg",alt:"Proyecto AG Business Networking"},
];

export default function HomeV4(){
 const [decision,setDecision]=useState(null);
 const recommendation=decisions.find(i=>i.id===decision);
 return <main>
  <header className="siteHeader"><nav className="nav shell" aria-label="Navegación principal"><a className="brand brandOfficial" href="#inicio" aria-label="Compás Evolution, inicio"><Image src="/brand/compas-evolution-official.png" alt="Compás Evolution" width={235} height={81} priority/></a><div className="navLinks"><a href="#soluciones">Soluciones</a><a href="#elige">Encuentra tu ruta</a><a href="#agentes">Agentes</a><a href="#casos">Casos</a></div><a className="navCta" href={APP_URL} target="_blank" rel="noreferrer">Entrar a Compás One <span>↗</span></a></nav></header>

  <section className="hero" id="inicio"><div className="heroGlow"/><div className="heroGrid"/><div className="heroAurora heroAuroraOne"/><div className="heroAurora heroAuroraTwo"/><div className="shell heroInner"><div className="heroCopy"><p className="eyebrow"><span/> Compás Evolution</p><h1>Decide con claridad.<br/><em>Avanza con dirección.</em></h1><p className="heroLead">Un ecosistema que conecta operación, aprendizaje, creación e inteligencia artificial para convertir necesidades reales en rutas concretas de acción.</p><div className="heroActions"><a className="button buttonPrimary" href="#soluciones">Explorar el ecosistema ↓</a><a className="button buttonGhost" href="#elige">Encontrar mi ruta →</a></div><div className="heroProof"><span><b>Compás One</b>Opera y organiza</span><span><b>Academy</b>Aprende y aplica</span><span><b>Creators</b>Crea y publica</span><span><b>Compás IA</b>Atiende y evoluciona</span></div></div><div className="heroVisual ecosystemVisualHero"><div className="visualLabel"><span/> Un ecosistema · Cuatro capacidades</div><div className="ecosystemOrbit orbitOuter"/><div className="ecosystemOrbit orbitInner"/><div className="ecosystemCore glassPanel"><Image src="/brand/compas-evolution-halcon.svg" alt="Halcón de Compás Evolution" width={120} height={120}/><p>COMPÁS</p><strong>EVOLUTION</strong><small>Una visión. Un rumbo.</small></div><div className="ecosystemNode nodeOne glassPanel"><span>01</span><div><b>Compás One</b><small>Operar</small></div></div><div className="ecosystemNode nodeAcademy glassPanel"><span>02</span><div><b>Academy</b><small>Aprender</small></div></div><div className="ecosystemNode nodeCreators glassPanel"><span>03</span><div><b>Creators</b><small>Crear</small></div></div><div className="ecosystemNode nodeAi glassPanel"><span>04</span><div><b>Compás IA</b><small>Evolucionar</small></div></div></div></div></section>

  <section className="decisionBar"><div className="shell decisionBarInner"><p>No necesitas más opciones.</p><h2>Necesitas saber cuál es la correcta para ti.</h2><a href="#elige">Descúbrelo en menos de un minuto →</a></div></section>

  <section className="section shell" id="soluciones"><div className="sectionHeader"><div><p className="eyebrow dark"><span/> Cuatro capacidades conectadas</p><h2>Empieza por lo que necesitas hoy.</h2></div><p>Cada división puede funcionar por sí sola y también conectarse con las demás cuando el proyecto crece.</p></div><div className="productGrid"><article className="productCard oneCard"><div className="productTop"><Image src="/brand/compas-one-logo.svg" alt="Compás One" width={512} height={512}/><span>OPERACIÓN</span></div><div className="productCopy"><p className="productKicker">El núcleo operativo</p><h3>Clientes, conversaciones y seguimiento.</h3><p>Ordena la operación y conecta CRM, agenda, automatizaciones y agentes inteligentes.</p><ul><li>CRM y contactos</li><li>Seguimiento centralizado</li><li>Automatizaciones y agentes</li></ul><a href="/compas-one">Conocer Compás One →</a></div></article><article className="productCard academyCard"><div className="productTop"><Image src="/brand/compas-academy-logo.svg" alt="Compás Academy" width={512} height={512}/><span>APRENDIZAJE</span></div><div className="productCopy"><p className="productKicker">Aprendizaje aplicable</p><h3>Aprende lo necesario. Aplícalo con propósito.</h3><p>Rutas, cursos y recursos conectados con objetivos y proyectos reales.</p><ul><li>Cursos y rutas</li><li>Recursos del alumno</li><li>Academias personalizadas</li></ul><a href="/compas-academy">Conocer Compás Academy →</a></div></article></div></section>

  <HomeGrowth/>

  <section className="finderSection" id="elige"><div className="shell finderGrid"><div className="finderIntro"><p className="eyebrow light"><span/> Orientador Compás</p><h2>¿Qué quieres resolver en este momento?</h2><p>Selecciona la opción que más se parece a tu situación. Te mostraremos un buen punto de partida.</p></div><div className="finderPanel">{!recommendation?<><p className="panelLabel">ELIGE UNA OPCIÓN</p><div className="choiceList">{decisions.map(item=><button key={item.id} type="button" onClick={()=>setDecision(item.id)}><span>{item.label}</span><b>→</b></button>)}</div><small>No necesitas registrarte para recibir una recomendación.</small></>:<div className="recommendation" aria-live="polite"><p className="panelLabel">RUTA RECOMENDADA</p><h3>{recommendation.title}</h3><p>{recommendation.text}</p><a className="button buttonPrimary" href={recommendation.href} data-compas-agent={recommendation.agent} data-compas-product={recommendation.product}>{recommendation.cta} →</a><button className="resetButton" type="button" onClick={()=>setDecision(null)}>Elegir otra necesidad</button></div>}</div></div></section>

  <section className="portfolioSection" id="proyectos"><div className="shell"><div className="portfolioHeader"><div><p className="eyebrow dark"><span/> Proyectos en acción</p><h2>Ideas convertidas en experiencias reales.</h2></div><div className="portfolioIntro"><p>Diseñamos soluciones alrededor de la necesidad: página, academia, contenido, captación, soporte y seguimiento.</p></div></div><div className="portfolioGrid paginas">{projects.map((p,i)=><article className="portfolioCard" key={p.title}><div className="portfolioImage"><Image src={p.image} alt={p.alt} width={1400} height={788}/><span>{String(i+1).padStart(2,"0")}</span></div><div className="portfolioMeta"><h3>{p.title}</h3><p>{p.type}</p></div></article>)}</div><div className="portfolioFoot"><p>Cada proyecto inicia con una necesidad distinta.</p><a href="#agente-ventas" data-compas-agent="sales" data-compas-product="compas-creators">Quiero desarrollar mi proyecto →</a></div></div></section>

  <section className="ecosystem shell"><div className="ecosystemCopy"><p className="eyebrow light"><span/> Más que una plataforma</p><h2>Un ecosistema que crece contigo.</h2><p>Empieza por lo que necesitas hoy. Cuando tu proyecto avance, conecta nuevas capacidades sin perder continuidad.</p><a href="#agente-ventas" data-compas-agent="sales" data-compas-product="diagnostico">Hablar con un orientador →</a></div><div className="ecosystemVisual"><div className="orbit orbitOne"/><div className="orbit orbitTwo"/><div className="robotWrap"><Image src="/brand/compas-evolution-halcon.svg" alt="Halcón de Compás Evolution" width={640} height={640}/></div><div className="orbitTag tagOne">ONE</div><div className="orbitTag tagTwo">ACADEMY</div><div className="orbitTag tagThree">CREATORS</div></div></section>

  <section className="finalCta shell"><p className="eyebrow"><span/> Tu siguiente paso</p><h2>La claridad empieza con una buena conversación.</h2><p>Habla con el agente adecuado según lo que necesitas.</p><div className="finalActions"><a className="button buttonPrimary" href="#agente-ventas" data-compas-agent="sales" data-compas-product="diagnostico">Quiero orientación →</a><a className="button buttonLight" href="#agente-soporte" data-compas-agent="support">Necesito soporte</a><a className="button buttonLight" href="#agente-seguimiento" data-compas-agent="followup">Dar seguimiento</a></div></section>

  <footer><div className="shell footerInner"><Image src="/brand/compas-evolution-horizontal.svg" alt="Compás Evolution" width={250} height={64}/><p>Operación · Aprendizaje · Creación · Inteligencia artificial</p><div className="footerMap"><section><strong>Ecosistema</strong><a href="/compas-one">Compás One</a><a href="/compas-academy">Compás Academy</a><a href="/compas-creators">Compás Creators</a><a href="/compas-ia">Compás IA</a></section><section><strong>Atención</strong><a href="#agente-ventas" data-compas-agent="sales">Ventas</a><a href="#agente-soporte" data-compas-agent="support">Soporte</a><a href="#agente-seguimiento" data-compas-agent="followup">Seguimiento</a></section><section><strong>Accesos</strong><a href={APP_URL} target="_blank" rel="noreferrer">Compás One</a><a href={ACADEMY_URL} target="_blank" rel="noreferrer">Aula Compás</a><a href="#casos">Casos</a><a href="#preguntas">FAQ</a></section><section><strong>Legal</strong><a href="/privacidad">Privacidad</a><a href="/terminos">Términos</a><a href="/cookies">Cookies</a><a href="/ia-y-datos">IA y datos</a><a href="/derechos-de-autor">Derechos de autor</a></section></div><small>© {new Date().getFullYear()} Compás Evolution. Todos los derechos reservados.</small></div></footer>
 </main>
}
